---
- hosts: all
  roles:
    - { role: Aplyca.Essentials }
  post_tasks:
    - name: Test if Lynx is installed
      shell: "lynx --version"
    - name: Test if Git is installed
      shell: "git --version"
    - name: Test if Wget is installed
      shell: "wget --version"
    - name: Test if ShellShock is patched
      shell: "env x='() { :;}; echo vulnerable' bash -c 'echo hello' | grep -q 'vulnerable' && (exit 1) || (exit 0)"
    - name: Check date
      shell: "date | grep -q 'EDT' && (exit 0) || (exit 1)"
