---
- debug: var=essentials verbosity=1
  tags: vars
  
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup.yml
