---
- debug: var=essentials verbosity=1
  tags: vars

- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: setup.yml
