---
- name: Update packages repos
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: essentials["update"]

- name: Upgrade the system
  sudo: yes
  apt:
    upgrade: dist
    cache_valid_time: 86400
  when: essentials["upgrade"]

- name: Ensure essentials packages are present using apt
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: essentials["packages"]
