---
- name: Upgrade the system
  become: yes
  yum:
    name: "*"
    state: latest
  when: essentials.upgrade is defined and essentials.upgrade

- name: Ensure essentials packages are present using yum
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ essentials.packages }}"

- name: Add custom timezone
  become: yes
  command: "sudo timedatectl set-timezone {{ essentials.timezone | default('Etc/UTC') }}"
  changed_when: False

- name: Disable SELInux
  become: yes
  selinux:
    state: "{{ essentials.selinux }}"
  when: essentials.selinux is defined
