---
- name: Check the timezone
  command: cat /etc/timezone
  register: timezone
  changed_when: False

- name: Add custom timezone
  sudo: yes
  copy:
    content: "{{ essentials['timezone'] | default('Etc/UTC') }}"
    dest: /etc/timezone
  notify: reload tzdata
  when: timezone.stdout != (essentials['timezone'] | default('Etc/UTC'))

- name: Updating crontab
  cron:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    job: "cd {{ item.root | default('~') }} && {{ item.job }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
  with_items: essentials["crons"]
  when: essentials["crons"]

- name: Make sure that the .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Set up authorized_keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item }}"
  with_items: essentials['ssh']['authorized_keys']
  when: essentials['ssh']['authorized_keys']

- name: Send SSH config (host connections)
  template:
    src: home/ansible_user/.ssh/config.j2
    dest: ~/.ssh/config
    mode: 0600

- name: Add key to remote user
  copy:
    src: "{{ item.IdentityFileSource }}"
    dest: "~/.ssh/{{ item.IdentityFile }}"
    mode: 0400
  with_items: essentials["ssh"]["config"]
  when: essentials["ssh"]["config"]
