---
- name: Upgrade the system
  sudo: yes
  yum:
    name: "*"
    state: latest
    
- name: Ensure essentials packages are present using apt
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: essentials["packages"]

- name: Add custom timezone
  sudo: yes
  copy:
    content: "{{ essentials['timezone'] | default('Etc/UTC')}}"
    dest: /etc/timezone
  notify: reload tzdata
