---
- name: Upgrade PIP
  become: yes
  shell: "pip install --upgrade pip"
  tags: pip_packages

- name: Install Python libraries
  become: yes
  pip:
    name: "{{ item }}"
  with_items: "{{ essentials.pip_packages }}"
  tags: pip_packages

- name: Updating crontab
  cron:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    job: "cd {{ item.root | default('~') }} && {{ item.job }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
  with_items: "{{ essentials.crons }}"
  when: essentials.crons is defined
  tags: crontab

- name: Make sure that the .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Make sure the groups are presents
  become: yes
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.id | default('') }}"
  with_items: "{{ essentials.groups }}"
  tags: groups

- name: Make sure the users are configured
  become: yes
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default('') }}"
    groups: "{{ item.groups | default('') }}"
    uid: "{{ item.id | default('') }}"
    state: "{{ item.state | default('present') }}"
    createhome: "{{ item.createhome | default('yes') }}"
    append: yes
  with_items: "{{ essentials.users }}"
  tags: users

- name: Set up authorized_keys
  become: yes
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  with_items: "{{ essentials.ssh.authorized_keys }}"
  when: essentials.ssh.authorized_keys
  tags: authorized_keys

- name: Make sure SSH config is present
  template:
    src: home/ansible_user/.ssh/config.j2
    dest: ~/.ssh/config
    mode: 0600
  changed_when: False
  tags: ssh_keys

- name: Add keys to remote user
  copy:
    src: "{{ item.key }}"
    dest: ".ssh/{{ item.name }}"
    mode: 0400
  with_items: "{{ essentials.ssh.private_keys }}"
  tags: ssh_keys

- name: Make sure mount points are present
  become: yes
  file:
    path: "{{ item.path }}"
    mode: 0777
    state: directory
  with_items: "{{ essentials.mounts }}"

- name: Make sure devices are mounted
  become: yes
  mount:
    name: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.type | default('ext4') }}"
    opts: "{{ item.options | default('') }}"
    state: mounted
  with_items: "{{ essentials.mounts }}"

- name: Add directory to path
  lineinfile:
    dest: "~/.profile"
    line: 'if [ -d "{{ item }}" ]; then PATH="$PATH:{{ item | expanduser }}"; fi'
    state: present
  with_items: "{{ essentials.paths }}"
  tags: paths

- name: Make sure the file system ACLs are present
  acl:
     name: "{{ item.name }}"
     entity: "{{ item.entity  | default(ansible_user_id)}}"
     etype: "{{ item.etype | default('user') }}"
     permissions: "{{ item.permissions | default('rwx') }}"
     default: "{{ item.permissions | default('yes') }}"
     state: "{{ item.state | default('present') }}"
  with_items: "{{ essentials.acl }}"

- name: Create SSl Certificate directories
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
  with_items: "{{ essentials.ssl_certs }}"
  tags: certificates

- name: Create self-signed SSL certificate
  become: yes
  command: "openssl req -x509 -nodes -newkey {{ item.type | default('rsa') }}:{{ item.bits | default('2048') }} -subj '/C={{ item.CountryName | default('AU') }}/ST={{ item.StateName | default('Some-State') }}/O={{ item.OrganizationName | default('Internet Widgits Pty Ltd') }}/CN={{ item.CommonName | default('*.example.com') }}' -days {{ item.days | default('365') }} -keyout {{ item.name }}.key -out {{ item.name }}.crt -extensions v3_ca"
  args:
    chdir: "{{ item.path }}"
    creates: "{{ item.path }}/{{ item.name }}.crt"
  with_items: "{{ essentials.ssl_certs }}"
  tags: certificates

- name: Make sure the SSL certificates directories are present
  become: yes
  file:
    dest: "/etc/ssl/{{ item.name }}"
    state: directory
  with_items: "{{ essentials.certificates }}"
  when: item.name is defined
  no_log: "{{ essentials.no_log }}"
  tags: certificates

- name: Make sure the SSL certificates are present
  become: yes
  copy:
    content: "{{ item.crt }}"
    dest: "/etc/ssl/{{ item.name }}/certificate.crt"
  with_items: "{{ essentials.certificates }}"
  when: item.name is defined and item.crt is defined
  no_log: "{{ essentials.no_log }}"
  tags: certificates

- name: Make sure the SSL certificate keys are present
  become: yes
  copy:
    content: "{{ item.key }}"
    dest: "/etc/ssl/{{ item.name }}/certificate.key"
  with_items: "{{ essentials.certificates }}"
  when: item.name is defined and item.key is defined
  no_log: "{{ essentials.no_log }}"
  tags: certificates

- name: Make sure the SSL certificate intermediates are present
  become: yes
  copy:
    content: "{{ item.intermediate }}"
    dest: "/etc/ssl/{{ item.name }}/intermediate.crt"
  with_items: "{{ essentials.certificates }}"
  when: item.name is defined and item.intermediate is defined
  no_log: "{{ essentials.no_log }}"
  tags: certificates

- name: Make sure Git config is present
  git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  with_dict: "{{ essentials.git_config | default({}) }}"
  tags: git_config
