---
- name: Check the timezone
  command: cat /etc/timezone
  register: timezone
  changed_when: False

- name: Add custom timezone
  sudo: yes
  copy:
    content: "{{ essentials['timezone'] | default('Etc/UTC') }}"
    dest: /etc/timezone
  notify: reload tzdata
  when: timezone.stdout != (essentials['timezone'] | default('Etc/UTC'))

- name: Updating crontab
  cron:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    job: "cd {{ item.root | default('~') }} && {{ item.job }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
  with_items: essentials["crons"]
  when: essentials["crons"]

- name: Set up authorized_keys for the deploy user
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item }}"
  with_file: essentials['authorized_keys']
  when: essentials['authorized_keys']

