---
- debug: msg="Make sure {{ user.name }} exists"

- name: Make sure the user is present
  become: yes
  user:
    name: "{{ user.name }}"
    group: "{{ user.group | default(False) }}"
    groups: "{{ user.groups | default([]) }}"
    state: "{{ user.state | default('present') }}"
    createhome: "{{ user.createhome | default('yes') }}"
    append: yes
  tags: essentials_users

- name: Make sure user exists in sudoer
  become: yes
  lineinfile:
    dest: /etc/sudoers.d/81-users
    state: present
    regexp: '^{{ user.name }}\s'
    line: "{{ user.name }} ALL=(ALL:ALL){% if user.sudo.no_password | default(false) %} NOPASSWD:{% endif %} ALL"
    validate: 'visudo -cf %s'
    create: yes
    mode: 0400
  when: user.sudo is defined and user.sudo.enabled | default(false)
  tags: essentials_users
