---
- name: reload tzdata
  become: yes
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: stop ntp
  become: yes
  service:
    name: ntp
    state: stopped

- name: update ntpd
  become: yes
  command: "ntpd -gq"

- name: start ntp
  become: yes
  service:
    name: ntp
    state: started
    enabled: yes

- name: restart ntp
  become: yes
  service:
    name: ntp
    state: restarted
